/* MIT License
 * Copyright (c) 2019 TAKESHI MIURA
 * https://github.com/tksmiura/color_log
 */
#include "color_log.h"

/* test macros */

int main(int argc, char *argv[])
{
    printf("color_log.h defined macros...\n\n");

    printf(COLOR_BG_BLACK "COLOR_BG_BLACK" COLOR_RESET "\n");
    printf(COLOR_BG_RED "COLOR_BG_RED" COLOR_RESET "\n");
    printf(COLOR_BG_GREEN "COLOR_BG_GREEN" COLOR_RESET "\n");
    printf(COLOR_BG_YELLOW "COLOR_BG_YELLOW" COLOR_RESET "\n");
    printf(COLOR_BG_BLUE "COLOR_BG_BLUE" COLOR_RESET "\n");
    printf(COLOR_BG_MAGENTA "COLOR_BG_MAGENTA" COLOR_RESET "\n");
    printf(COLOR_BG_CYAN "COLOR_BG_CYAN" COLOR_RESET "\n");
    printf(COLOR_BG_WHITE "COLOR_BG_WHITE" COLOR_RESET "\n");

    printf(COLOR_BG_LBLACK "COLOR_BG_LBLACK" COLOR_RESET "\n");
    printf(COLOR_BG_LRED "COLOR_BG_LRED" COLOR_RESET "\n");
    printf(COLOR_BG_LGREEN "COLOR_BG_LGREEN" COLOR_RESET "\n");
    printf(COLOR_BG_LYELLOW "COLOR_BG_LYELLOW" COLOR_RESET "\n");
    printf(COLOR_BG_LBLUE "COLOR_BG_LBLUE" COLOR_RESET "\n");
    printf(COLOR_BG_LMAGENTA "COLOR_BG_LMAGENTA" COLOR_RESET "\n");
    printf(COLOR_BG_LCYAN "COLOR_BG_LCYAN" COLOR_RESET "\n");
    printf(COLOR_BG_LWHITE "COLOR_BG_LWHITE" COLOR_RESET "\n");

    printf(COLOR_FG_BLACK "COLOR_FG_BLACK" COLOR_RESET "\n");
    printf(COLOR_FG_RED "COLOR_FG_RED" COLOR_RESET "\n");
    printf(COLOR_FG_GREEN "COLOR_FG_GREEN" COLOR_RESET "\n");
    printf(COLOR_FG_YELLOW "COLOR_FG_YELLOW" COLOR_RESET "\n");
    printf(COLOR_FG_BLUE "COLOR_FG_BLUE" COLOR_RESET "\n");
    printf(COLOR_FG_MAGENTA "COLOR_FG_MAGENTA" COLOR_RESET "\n");
    printf(COLOR_FG_CYAN "COLOR_FG_CYAN" COLOR_RESET "\n");
    printf(COLOR_FG_WHITE "COLOR_FG_WHITE" COLOR_RESET "\n");

    printf(COLOR_FG_LBLACK "COLOR_FG_LBLACK" COLOR_RESET "\n");
    printf(COLOR_FG_LRED "COLOR_FG_LRED" COLOR_RESET "\n");
    printf(COLOR_FG_LGREEN "COLOR_FG_LGREEN" COLOR_RESET "\n");
    printf(COLOR_FG_LYELLOW "COLOR_FG_LYELLOW" COLOR_RESET "\n");
    printf(COLOR_FG_LBLUE "COLOR_FG_LBLUE" COLOR_RESET "\n");
    printf(COLOR_FG_LMAGENTA "COLOR_FG_LMAGENTA" COLOR_RESET "\n");
    printf(COLOR_FG_LCYAN "COLOR_FG_LCYAN" COLOR_RESET "\n");
    printf(COLOR_FG_LWHITE "COLOR_FG_LWHITE" COLOR_RESET "\n");

    printf(COLOR_UNDERLINE  "COLOR_UNDERLINE" COLOR_RESET "\n");
    printf(COLOR_BOLD  "COLOR_BOLD" COLOR_RESET "\n");
    printf(COLOR_REVERSE  "COLOR_REVERSE" COLOR_RESET "\n");

    printf(COLOR_RESET "COLOR_RESET(reset color settings)\n");
}
